export const users = [
  {
    id: 1,
    username: "Ryan",
    email: "ryan@test.com",
    password: "1234",
    level: 10,
    xp: 1000,
    gems: 1000,
    streak: 21,
  },
  {
    id: 2,
    username: "Emily",
    email: "emily@test.com",
    password: "1234",
    level: 9,
    xp: 950,
    gems: 1200,
    streak: 30,
  },
  {
    id: 3,
    username: "Jordan",
    email: "jordan@test.com",
    password: "1234",
    level: 21,
    xp: 2105,
    gems: 100,
    streak: 0,
  },
  {
    id: 4,
    username: "Gisell",
    email: "gisell@test.com",
    password: "1234",
    level: 3,
    xp: 300,
    gems: 200,
    streak: 3,
  },
];
