// export const tasks = [
//   { id: 1, name: "Clean Desk", gems: 10, icon: "🧹", completed: false },
//   { id: 2, name: "Clean Park", gems: 25, icon: "🏞️", completed: false },
//   { id: 3, name: "Laundry", gems: 10, icon: "🧺", completed: false },
//   { id: 4, name: "Clean Bathroom", gems: 15, icon: "🧴", completed: false },
//   { id: 5, name: "Clean Kitchen", gems: 20, icon: "🍽️", completed: false },
//   { id: 6, name: "Take out Trash", gems: 5, icon: "🗑️", completed: false },
//   { id: 7, name: "Mop Floors", gems: 15, icon: "🧹", completed: false },
//   { id: 8, name: "Dust Surfaces", gems: 10, icon: "🧽", completed: false },
//   { id: 9, name: "Wipe Windows", gems: 20, icon: "🧽", completed: false },
//   { id: 10, name: "Clean Fridge", gems: 25, icon: "🧊", completed: false },
//   { id: 11, name: "Organize Closet", gems: 20, icon: "👚", completed: false },
//   { id: 12, name: "Sweep Porch", gems: 10, icon: "🧹", completed: false },
//   { id: 13, name: "Change Bed Sheets", gems: 10, icon: "🛏️", completed: false },
//   { id: 14, name: "Clean Microwave", gems: 10, icon: "🧼", completed: false },
//   { id: 15, name: "Take out Recycling", gems: 5, icon: "♻️", completed: false },
// ];
